environment: production

domain: estimates.data.mayflower.tech

images:
  app:
    image: ghcr.io/mayflower/esti-mates/mf-estimates
    tag: latest # managed by argocd-image-updater

config:
  BRAND_NAME: "Mayflower GmbH"
  BRAND_LOGO_URL: "/assets/mayflower-logo.svg"
  BRAND_PRIMARY_COLOR: "#1a73e8"
  BRAND_FOOTER_TEXT: "Part of Mayflower Agile Tools"
